// Default categories for the app
import { Category } from '@/types';

export const DEFAULT_EXPENSE_CATEGORIES: Category[] = [
  {
    id: 'makanan',
    name: 'Makanan & Minuman',
    type: 'expense',
    color: '#FF6B6B',
    icon: '🍔',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'transportasi',
    name: 'Transportasi',
    type: 'expense',
    color: '#4ECDC4',
    icon: '🚗',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'belanja',
    name: 'Belanja',
    type: 'expense',
    color: '#FFE66D',
    icon: '🛍️',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tagihan',
    name: 'Tagihan',
    type: 'expense',
    color: '#95E1D3',
    icon: '📱',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'kesehatan',
    name: 'Kesehatan',
    type: 'expense',
    color: '#F38181',
    icon: '⚕️',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hiburan',
    name: 'Hiburan',
    type: 'expense',
    color: '#AA96DA',
    icon: '🎮',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pendidikan',
    name: 'Pendidikan',
    type: 'expense',
    color: '#FCBAD3',
    icon: '📚',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rumah-tangga',
    name: 'Rumah Tangga',
    type: 'expense',
    color: '#A8D8EA',
    icon: '🏠',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'komunikasi',
    name: 'Komunikasi',
    type: 'expense',
    color: '#FFB6B9',
    icon: '📞',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'lainnya-expense',
    name: 'Lainnya',
    type: 'expense',
    color: '#D4A5A5',
    icon: '📌',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_INCOME_CATEGORIES: Category[] = [
  {
    id: 'gaji',
    name: 'Gaji',
    type: 'income',
    color: '#6BCB77',
    icon: '💼',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bonus',
    name: 'Bonus',
    type: 'income',
    color: '#4D96FF',
    icon: '🎉',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'penjualan',
    name: 'Penjualan',
    type: 'income',
    color: '#FFD166',
    icon: '📊',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'investasi',
    name: 'Investasi',
    type: 'income',
    color: '#06D6A0',
    icon: '📈',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'freelance',
    name: 'Freelance',
    type: 'income',
    color: '#EF476F',
    icon: '💻',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pemasukan-lain',
    name: 'Pemasukan Lain',
    type: 'income',
    color: '#FFB703',
    icon: '💰',
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_WALLETS = [
  {
    id: 'cash',
    name: 'Tunai',
    type: 'cash' as const,
    balance: 0,
    currency: 'IDR',
    color: '#FF6B6B',
    icon: '💵',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'dana',
    name: 'Dana',
    type: 'digital' as const,
    balance: 0,
    currency: 'IDR',
    color: '#1F9FFF',
    icon: '📲',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bca',
    name: 'BCA',
    type: 'bank' as const,
    balance: 0,
    currency: 'IDR',
    color: '#1F88DD',
    icon: '🏦',
    createdAt: new Date().toISOString(),
  },
];
